### ISSUE TITLE
这三个网站在扩充指南的时候可以参考下

### ISSUE THREAD

**Issue by yomyo** [ArchLinuxStudio/ModernSecurityProtectionGuide#1]
https://prism-break.org/zh-CN/
https://www.privacytools.io/
https://restoreprivacy.com/

还有这个仓库提供了非常全面的谷歌替代品
https://github.com/tycrek/degoogle

**Comment by ryosukeeeeee** [comment]
@yomyo They are very useful websites, thank you. We will consider adding appropriate content in the future.
